#!/usr/bin/env bash
set -euo pipefail
ROOT=$(cd "$(dirname "$0")/.." && pwd)
INC="$ROOT/PlayTools/MetalCapture/PTMetalCapture.inc"
[[ $(grep -c 'objc_getClassList' "$INC") -eq 2 ]]
! grep -nE 'getBytes:|AGX|IOGPU' "$INC"
grep -q 'ptmc_class_implements_selector' "$INC"
grep -q 'ptmc_method_owner' "$INC"
grep -q 'ptmc_install_owner_hook' "$INC"
grep -q 'command-buffer fallback hooks' "$INC"
grep -q 'CGColorSpaceCreateWithName(kCGColorSpaceSRGB)' "$INC"
grep -q 'setColorspace:' "$INC"
grep -q 'ptmc_uninstall_runtime_hooks' "$INC"
grep -q 'native Metal dispatch restored' "$INC"
grep -q 'direct CAMetalDrawable hooks' "$INC"
grep -q 'Capture heartbeat updated' "$INC"
grep -q '_Thread_local PTMCImpCacheEntry' "$INC"
grep -q '_dyld_register_func_for_add_image' "$INC"
grep -q 'dispatch_async(session.encoderQueue' "$INC"
grep -q 'kCVPixelFormatType_420YpCbCr8BiPlanarVideoRange' "$INC"
grep -q 'RequireHardwareAcceleratedVideoEncoder' "$INC"
grep -q 'kCMVideoCodecType_AppleProRes422LT' "$INC"
grep -q 'kCMVideoCodecType_AppleProRes422HQ' "$INC"
grep -q 'kCVPixelFormatType_32BGRA' "$INC"
grep -q 'MTLBlitCommandEncoder' "$INC"
grep -q 'PTMC_CODEC' "$INC"
grep -q 'skippedRate' "$INC"
grep -q '_nextCaptureTick' "$INC"
grep -q 'ptmc_drawable_present' "$INC"
grep -q 'session.commandQueue' "$INC"
grep -q 'PTMC_OUTPUT_DIR' "$INC"
grep -q 'ptmc_set_wants_edr' "$INC"
grep -q 'PTMC hooks loaded and waiting for capture commands' "$INC"
grep -q 'PTMC Config' "$INC"
grep -q 'PTMC_STATUS_FILE' "$INC"
grep -q 'PTMC_FORCE_SDR_DISPLAY' "$INC"
grep -q 'partial.mov' "$INC"
grep -q 'io.playcover.ptmc.start.%@' "$INC"
grep -q 'io.playcover.ptmc.stop.%@' "$INC"
grep -q '#include "MetalCapture/PTMetalCapture.inc"' "$ROOT/PlayTools/PlayLoader.m"
! grep -q 'ptmc_next_drawable_original' "$INC"
echo 'PTMC static invariants: PASS'
grep -q 'frame hooks are dormant until Start' "$INC"
! grep -q 'ptmc_next_drawable' "$INC"
grep -q 'cid \* 2u' "$INC"
grep -q '(session.width + 1) / 2' "$INC"
grep -q 'ptmc_restore_capture_layer' "$INC"
grep -q '_originalFramebufferOnly' "$INC"
grep -q '_layerNeedsRefresh' "$INC"
grep -q 'captureIntervalTicks' "$INC"
grep -q 'ptmc_ns_to_ticks' "$INC"
grep -q 'ptmc_call_original_bool_setter' "$INC"
grep -q 'PTMC_RESOLUTION_MODE' "$INC"
grep -q 'PTMC_CAPTURE_WIDTH' "$INC"
grep -q 'PTMC_CAPTURE_HEIGHT' "$INC"
grep -q 'PTMC_SUPPRESS_DISPLAY' "$INC"
grep -q 'ptmc_bgra_to_nv12_scaled' "$INC"
grep -q 'ptmc_bgra_scale_copy' "$INC"
grep -q 'IOSurface CVPixelBuffer -> VideoToolbox (no CPU readback)' "$INC"
grep -q 'layer.opacity = desiredOpacity' "$INC"
grep -q 'PTMC_SKIP_DISPLAY_PRESENT' "$INC"
grep -q 'ptmc_should_skip_display_present' "$INC"
grep -q 'lastOwnedCaptureGPUTimeUs' "$INC"
grep -q 'displayPresentSkipped' "$INC"

grep -q '_pendingWrites' "$INC"
grep -q 'io.playcover.ptmc.writer' "$INC"
grep -q 'samplingSkipPerSecond' "$INC"
grep -q 'Deadline-based sampling' "$INC"

grep -q 'presentFPS' "$INC"
grep -q 'captureFPS' "$INC"
grep -q 'encodedFPS' "$INC"