#!/usr/bin/env bash
set -euo pipefail
ROOT=$(cd "$(dirname "$0")/.." && pwd)
INC="$ROOT/PlayTools/MetalCapture/PTMetalCapture.inc"
[[ $(grep -c 'objc_getClassList' "$INC") -eq 2 ]]
! grep -nE 'getBytes:|AGX|IOGPU' "$INC"
grep -q 'ptmc_class_implements_selector' "$INC"
grep -q 'ptmc_method_owner' "$INC"
grep -q 'ptmc_install_owner_hook' "$INC"
grep -q 'command-buffer fallback hooks' "$INC"
grep -q 'CGColorSpaceCreateWithName(kCGColorSpaceSRGB)' "$INC"
grep -q 'setColorspace:' "$INC"
grep -q 'ptmc_uninstall_runtime_hooks' "$INC"
grep -q 'native Metal dispatch restored' "$INC"
grep -q 'direct CAMetalDrawable hooks' "$INC"
grep -q 'Capture heartbeat updated' "$INC"
grep -q '_Thread_local PTMCImpCacheEntry' "$INC"
grep -q '_dyld_register_func_for_add_image' "$INC"
grep -q 'dispatch_async(session.encoderQueue' "$INC"
grep -q 'kCVPixelFormatType_420YpCbCr8BiPlanarVideoRange' "$INC"
grep -q 'RequireHardwareAcceleratedVideoEncoder' "$INC"
grep -q 'kCMVideoCodecType_AppleProRes422LT' "$INC"
grep -q 'kCMVideoCodecType_AppleProRes422HQ' "$INC"
grep -q 'PTMC_CODEC' "$INC"
grep -q 'skippedRate' "$INC"
grep -q '_lastCaptureTick' "$INC"
grep -q 'ptmc_drawable_present' "$INC"
grep -q 'session.commandQueue' "$INC"
grep -q 'PTMC_OUTPUT_DIR' "$INC"
grep -q 'ptmc_set_wants_edr' "$INC"
grep -q 'PTMC hooks loaded and waiting for capture commands' "$INC"
grep -q 'PTMC Config' "$INC"
grep -q 'PTMC_STATUS_FILE' "$INC"
grep -q 'PTMC_FORCE_SDR_DISPLAY' "$INC"
grep -q 'partial.mov' "$INC"
grep -q 'io.playcover.ptmc.start.%@' "$INC"
grep -q 'io.playcover.ptmc.stop.%@' "$INC"
grep -q '#include "MetalCapture/PTMetalCapture.inc"' "$ROOT/PlayTools/PlayLoader.m"
! grep -q 'ptmc_next_drawable_original' "$INC"
echo 'PTMC static invariants: PASS'
grep -q 'frame hooks are dormant until Start' "$INC"
! grep -q 'ptmc_next_drawable' "$INC"
